#include <stdexcept>


int main()
{
    try
    {

    }
    catch (const std::overflow_error& oe)
    {

    }
    catch (const std::runtime_error& re)
    {

    }
    catch(const std::exception& e)
    {

    }

    return 0;
}
